interface Itodo {
    id: number,
    title: string,
    description: string,
    category: string,
    status: string,
    startDate: string,
    endDate: string,
}

export const todos: Itodo[] = [
    {
        id: 1,
        title: "Finish React Project",
        description: "Complete the frontend components and integrate with backend API.",
        category: "Work",
        status: "pending",
        startDate: "2025-09-01",
        endDate: "2025-09-05",
    },
    {
        id: 2,
        title: "Grocery Shopping",
        description: "Buy vegetables, fruits, and weekly essentials.",
        category: "Personal",
        status: "completed",
        startDate: "2025-08-30",
        endDate: "2025-08-30",
    },
    {
        id: 3,
        title: "Gym Workout",
        description: "Leg day workout including squats and lunges.",
        category: "Health",
        status: "pending",
        startDate: "2025-09-03",
        endDate: "2025-09-03",
    },
    {
        id: 4,
        title: "Prepare Presentation",
        description: "Create slides for Monday’s client meeting.",
        category: "Work",
        status: "pending",
        startDate: "2025-09-02",
        endDate: "2025-09-06",
    },
    {
        id: 5,
        title: "Read Book",
        description: "Finish reading 'Atomic Habits' before weekend.",
        category: "Personal Development",
        status: "completed",
        startDate: "2025-08-25",
        endDate: "2025-08-31",
    },
    {
        id: 6,
        title: "Doctor Appointment",
        description: "Visit Dr. Sharma for routine check-up.",
        category: "Health",
        status: "pending",
        startDate: "2025-09-04",
        endDate: "2025-09-04",
    },
    {
        id: 7,
        title: "Plan Trip",
        description: "Research hotels and flights for Goa trip.",
        category: "Travel",
        status: "pending",
        startDate: "2025-09-01",
        endDate: "2025-09-10",
    },
];
